apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommers-deployment
  namespace: default

spec:
  replicas: 3

  selector:
    matchLabels:
      app: ecommers

  template:
    metadata:
      labels:
        app: ecommers

    spec:
      containers:
        - name: ecommers-container
          image: rudhra2710/ecommers-flask-app:build-19
          ports:
            - containerPort: 5000
